### ISSUE TITLE
Machine config touches DISTRO settings

### ISSUE THREAD

**Issue by koenkooi** [ARM-software/meta-mali#2]
Floating point ABI is a DISTRO setting in OE, not a machine setting. 

https://github.com/ARM-software/meta-mali/blob/master/conf/machine/odroidxu3.conf#L8 should get commented.

Apart from it not being allowed, you are picking the wrong tune, you should be using one of the armv7athf tunes, otherwise the packages won't be installable on other armv7a architectures.

If you want to enforce hardfloat, you should recommend people to add something like this to their DISTRO.conf or local.conf:

https://github.com/Angstrom-distribution/meta-angstrom/blob/master/conf/distro/include/arm-defaults.inc

**Comment by gtucker-arm** [comment]
Fixed in meta-mali-004.
